FROM golang:1.17 as  build

# Build Delve
RUN go get github.com/go-delve/delve/cmd/dlv

ADD . /dockerdev
WORKDIR /dockerdev

RUN go build -gcflags="all=-N -l" -o /easytunnel ./cmd

# Final stage
FROM debian:buster

EXPOSE 40000

RUN mkdir "/easytunnel"
WORKDIR "/easytunnel"

COPY --from=build /go/bin/dlv ./
COPY --from=build /easytunnel ./

CMD ["./dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "./easytunnel"]