FROM openjdk:16

COPY ./build/libs/easysshtunnel.jar /tmp
WORKDIR /tmp
#CMD ["java", "-jar", "easysshtunnel.jar"]

CMD ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005", "-jar", "easysshtunnel.jar"]